### PR TITLE
Fix all build warnings and pass distcheck

### PR DESCRIPTION
**Pull request by davekeogh**
Greetings,

I took the liberty to fix the build warnings and a few other minor issues to get this to pass make distcheck.

If you're too busy to work on this anymore then I think it's best to just make some sort of release. Then it can get picked up by distros and maybe someone else will come along and work on it. I don't feel like working on any of the feature requests either. It works as well as I need it to. =)

### CODE REVIEW

**Comment by nsz32** [comment]
Wow, thank you for all you work !
Yes, i don't have many times for me now, but i will take evenings to make things clean and close some topics.
What we need to do to make a release ?

**Comment by davekeogh** [comment]
I built some example tarballs already and versioned them 0.1.0. Take a look here: https://github.com/davekeogh/xfce4-docklike-plugin/releases

With the the changes to the Makefiles and configure.ac.in, running make distcheck will basically configure, make, and make source tarballs. So if all that passes, it is ready to to release.

**Comment by SwampRabbit** [comment]
@davekeogh @nsz32 just wanted to let you know that I pulled that 0.1.0 tarball down and it packages up just fine for Debian 10 (Xfce 4.14).  I will test in MX Linux 19 with both Xfce 4.14.2 and 4.16 next.

Did id quick testing only with it in a VM, but I'll do a bit more longer testing over the next few days, because the last few versions had some minor oddities like apps falling in and out of the dock sometimes (shown then not shown).

Really great job, thanks for all the extra efforts.  I have been loving this application since it was NMT New Minimalist Dock, I know our users will too now that it has really matured.  I don't care about new/more features myself, I think it is great the way it is.

**Comment by nsz32** [comment]
Applications shouldn't disappear if you don't restart the panel. It's a startup bug : if the plugin is started with already applications launched, some are not detected. This is something  i want to fix before a proper release.

Thank you all two for your help. Will try distcheck soon.

**Pull request merged**
