### PR TITLE
Add a setting to show only windows from the current workspace

### PR DESCRIPTION
**Pull request by davekeogh**
Adds a feature requested in #16 

This seems to work for me, but could probably be improved. I'm not sure about the language for the setting either.

### CODE REVIEW

**Comment by nsz32** [comment]
Thanks for you request ! I don't use any workspace so it is very helpful.

Your modification doesn't seems to affect drop down windows list, nor close all on right click.
Is is intended ? It can be defensible for me.
The modification also doesn't seems to take care of windows moving from one workspace to another, which is needed.
(What about a window on multiple workspace ?)

For me this feature should clearly be GroupWindow centric. It should be associated or removed from it's group when :
- the groupWindow is created or moved to another workspace
- the active workspace is changed
- the setting is changed

See GroupWindow::getInGroup GroupWindow::leaveGroup and GroupWindow::updateState

A great part of the modification should takes place in updateState, The only thing it should do is getInGroup or leaveGroup according to groupWindow state and workspace. (Hide or show menu will be then useless).
The getInGroup in constructor will be useless to, the prepared group (in constructor) should be stored as member.
Some signals should also call updateState, and the settings should call updateState from all groupWindows.
Just ensure getInGroup and leaveGroup can be called each twice and you are in.

This way the modifications should be quite minimalist, without adding any new layer (removing the hide/show), and the setting to shows only the current screen windows will be really easy. Can you try this ?

Don't forget to add you in the contributors (Plugin.cpp).

**Comment by davekeogh** [comment]
Thanks for the feedback. I haven't touched any Gobject or C++ in quite a while so I was sure there would be loads of issues. I'll work on this.

My intention with this is to be able to mimic the behavior of the plank dock (and similar) which I and a lot of other users use in addition to the Xfce panel.

**Comment by nsz32** [comment]
I found your code quite readable, so this is cool.
The only drawback is that it adds a new layer of logic that can be avoided easily.
For sure you just get in the code and can't get all about it.

Yes, this feature is requested by many users.

**Comment by davekeogh** [comment]
Give this another try. From my perspective this works (using my PC today), but there may be some edge cases I am missing.

**Comment by nsz32** [comment]
Very nice, thank you !

**Comment by nsz32** [comment]
The FIXME stuff was fixed by the g_object_ref(mItem);
When an gobject is removed from its container an internal references counter is decreased, if 0, the gobject is deleted, so we needed to increment the references counter with this call.
Thank you !
Next step : show only windows on the current screen

**Pull request merged**
