### PR TITLE
Fix issue #39

### PR DESCRIPTION
**Pull request by davekeogh**

### CODE REVIEW

**Comment by nsz32** [comment]
I think that e3b73c4 changes nothing ?!

**Comment by davekeogh** [comment]
Whoops. Go ahead and revert that.

**Comment by nsz32** [comment]
What's about the issue #39 ?

**Comment by davekeogh** [comment]
This issue only persists in one particular circumstance that is not that easy to reproduce and I'm not sure if it's even a bug.

If I have an application (Chrome in my instance) pinned on the dock on both screen 1 and screen 2 and I switch to a workspace with a Chrome window open on screen 1, but not screen 2. The pinned icon on screen 2 will be highlighted even though the window is on the other screen.

Does this make sense?

**Comment by nsz32** [comment]
Some. I will get a mini/hdmi adapter to test it.

**Pull request merged**
