### PR TITLE
Fixed japanese translation

### PR DESCRIPTION
**Pull request by Hayao0819**
Fixed typos and confusing words in #27 
However, I am currently identifying one issue.

As you can see in the image below, the dialog size is strangely large.
I think this is because it is a Japanese character double-byte character. (It is just speculation and has no basis)

スクリーンショット_2020-09-04_19-31-15

### CODE REVIEW

**Comment by nsz32** [comment]
Check with 0bca8a9.
This will reduce spacing for sure.

**Comment by nsz32** [comment]
One question just for you : does the <SUPER>+[1, 2, 3, ...] shortcuts work on you keyboard ?

**Comment by Hayao0819** [comment]
This is a screenshot of the distribution I am developing ([Alter Linux](https://github.com/FascodeNet/alterlinux)).
By default the Super key is set to the shortcut to open the Whisker Menu, so it doesn't work.
If you delete the interfering settings of Whisker menu, it will be as the following screen and you can start or switch the application.
AlterLinux-Test-2020-09-04-22-36-15

**Comment by Hayao0819** [comment]
I'm sorry I made a mistake in the image.
スクリーンショット_2020-09-04_22-43-56

**Comment by nsz32** [comment]
Wow, nice !
I'm always impressed about people developing a distro !
I wish you the best with your project !

**Comment by nsz32** [comment]
And I really like the logo of it :+1:

**Comment by Hayao0819** [comment]
Thank you very much. It help us  **very very very** much for the development. I was really impressed when I saw your this docklike plugin.It's not a separate launcher and window list like Xfce so far, this plugin is simple and very easy to use.

**Comment by nsz32** [comment]
I just understood thant Docklike is the default taskbar on your distro with Xfce flavour. That's awesome !
One glad guy in France now due to your project ;)
Thank you,

**Pull request merged**
