### PR TITLE
Show the tooltip for groups of 1 if noWindowsListIfSingle is true

### PR DESCRIPTION
**Pull request by davekeogh**

### CODE REVIEW

**Comment by davekeogh** [comment]
The editing desktop files thing doesn't totally work. The changes won't appear until the panel is reloaded, and exo-desktop-item-edit will create a new desktop file in ~/.local/share/applications if you're editing something that was in /usr/share/applications which means pinned apps don't get updated. Any advice on improving this?

**Comment by nsz32** [comment]
Really nice, I didn't think about the exo-desktop-thing !
Changes are needed in AppInfos stores to make the changes consistent : layering them by folder, etc ...
I will haven't got time until some weeks to make this changes ... (they are also necessary just for themselves)
We need also to provide a "Delete custom launcher" option in right click menu.
I didn't merge it now, but this is to follow.

**Comment by nsz32** [comment]
Everything looks bad in 4.16 :(
I'm really disappointed with this new version, CSDs aren't what most xfce users want.
What a shame.
I'm looking into reverting or, even moving to i3 ...

**Comment by davekeogh** [comment]
I don't mind the CSD to be honest. I think they look really good in nautilus etc. I dislike the inconsistency between the two window decoration styles though. In Gnome they look identical, but the applications with header bars have a few extra buttons. In Xfce 4.16 it's much more noticeable and annoys me.

**Pull request closed without merging**
