### PR TITLE
Only display window list if more than 1 instance of the window

### PR DESCRIPTION
**Pull request by RUSshy**
It should solve #11

### CODE REVIEW

**Comment by nsz32** [comment]
ty, i will integrate it into a small settings panel soon ;)

**Comment by SwampRabbit** [comment]
> ty, i will integrate it into a small settings panel soon ;)

@nsz32 you may want to look at what is being done here
https://github.com/TheNiteCoder/xfce4-mxdock-plugin/commit/ff6c88067f30ab9185b0a4a40046c7548240bedd

**Comment by nsz32** [comment]
Sure

**Comment by nsz32** [comment]
I tried your pull request, it hasn't affected the list behavior as expected.
See a5baa0e7b8e1be68690a9424433172b598f7c18a (GroupMenu.cpp) if you want to see the actual change.

**Pull request closed without merging**
